service: api

provider:
  name: aws
  runtime: nodejs8.10

functions:
  scrapePosts:
    handler: src/handlers/scrapePosts/index.handler
    events:
      - schedule: cron(0 12 * * ? *)
        
plugins:
  - serverless-offline
